server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 18080
  servlet:
    context-path: /redis
spring:
  datasource:
    password: joymeter@123
    url: jdbc:mysql://localhost:3306/deviceData
    username: root
  thymeleaf:
    cache: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
