server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 18080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deviceData?useSSL=false
    username: root
    password: Joymeter@123