server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 18080
#RocketMQ配置
apache:
  rocketmq:
    namesrvAddr: 192.168.31.168:9876
    producerGroupName: test-group
    transactionProducerGroupName: transactionProducerGroup
    consumerGroupName: comsumerGroup
    producerInstanceName: producerInstance
    consumerInstanceName: cosumerInstance
    producerTranInstanceName: producerTranInstance
    consumerBatchMaxSize: 1
    consumerBroadcasting: false
    subscribe: TopicTest1:TagA
    enableHisConsumer: false
    enableOrderConsumer: false
#配置mysql多环境,修改active属性即可
spring:
  profiles:
    active: product
---
spring:
  profiles: PC
  datasource:
    url: jdbc:mysql://192.168.31.26:3306/deviceData?useSSL=false
    username: root
    password: Joymeter@123
  # 缓存
  cache:
    type: redis
  #redis配置，往cjoy系统发送实时数据
  redis:
    database: 0
    #host: 47.93.21.73
    host: 127.0.0.1
    password: 123456
    port: 6379
    timeout: 1000ms
---
spring:
  profiles: product
  datasource:
    url: jdbc:mysql://localhost/deviceData?useSSL=false
    username: root
    password: Joymeter@123
  # 缓存
  cache:
    type: redis
  #redis配置，往cjoy系统发送实时数据
  redis:
    database: 0
    host: 39.106.25.214
    password: 123456
    port: 6379
    timeout: 1000ms